apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-dashboard-ingress
  labels:
    app: f1-platform
    component: minio
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - storage.f1-platform.zawalich.pl
      secretName: echo-tls
  rules:
  - host: storage.f1-platform.zawalich.pl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-dashboard-service
            port:
              number: 9001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  labels:
    app: f1-platform
    component: minio
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - minio.f1-platform.zawalich.pl
      secretName: echo-tls
  rules:
  - host: minio.f1-platform.zawalich.pl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-service
            port:
              number: 9000